name: CI
on:
  push:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
  pull_request:
    branches:
    - main
    paths:
    - src/**
    - ui/**
    - pom.xml
    - .github/workflows/*
jobs:
  test:
    uses: making/workflows/.github/workflows/maven-unit-test.yaml@main
  build-jvm-image:
    needs: test
    uses: making/workflows/.github/workflows/build-docker-image-maven-jvm.yaml@main
    with:
      image_name: image_jvm
      image_file: image.yaml
  save-image-jvm:
    needs: build-jvm-image
    uses: making/workflows/.github/workflows/save-images.yaml@main
    with:
      image_name: image_jvm
      image_file: image.yaml